# Generated by Django 5.2 on 2025-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="license",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Real Estate license"
            ),
        ),
    ]
