# Generated by Django 5.2 on 2025-08-19 12:49

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                default="Manila", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="country",
            field=django_countries.fields.CountryField(
                default="PH", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                default="Add a description...", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                default="1111", max_length=100, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="street_address",
            field=models.CharField(
                default="None", max_length=150, verbose_name="Street Address"
            ),
        ),
    ]
