# Generated by Django 5.2 on 2025-08-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Inquiries",
            new_name="Inquiry",
        ),
    ]
